version: '2.1'

services:

  tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-watch
    volumes:
      - profiles-etl-combiner-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test

  travis-tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run travis
    user: root
    volumes:
      - profiles-etl-combiner-tests-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

volumes:
  profiles-etl-combiner-tests-node_modules:
