version: '2.1'

services:

  base-app:
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}

  profiles-db-updater:
    extends:
      service: base-app
    volumes:
      - .:/code
    links:
    - mongo-db:mongo

  mongo-db:
    image: mongo:3.4
    ports:
      - 27017:27017
