version: '2.1'

services:

  base-app:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}
      AZURE_STORAGE_CONNECTION_STRING: '${AZURE_STORAGE_CONNECTION_STRING}'
      CONTAINER_NAME: ${CONTAINER_NAME}

  profiles-etl-combiner:
    extends:
      service: base-app
    volumes:
      - profiles-etl-combiner-node_modules:/code/node_modules
    links:
    - mongo-db:mongo

  mongo-db:
    image: mongo:3.4
    ports:
      - 27017:27017

volumes:
  profiles-etl-combiner-node_modules:
