version: '2.1'

services:

  tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-watch
    volumes:
      - .:/code
      - profiles-db-updater-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}
    links:
    - mongo-db:mongo

  travis-tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run travis
    user: root
    volumes:
      - .:/code
      - profiles-db-updater-tests-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
    - mongo-db:mongo

  travis-snyk:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run start
    user: root
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
    - mongo-db:mongo

  mongo-db:
    image: mongo:3.4
    ports:
      - 27017:27017
volumes:
  profiles-db-updater-tests-node_modules:
