version: '2'
services:

  profiles-db-updater:
    image: nhsuk/profiles-db-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_HOST: profiles-db.profiles-db
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}
    labels:
      io.rancher.container.pull_image: always
