version: '2'
services:

  base-app:
    image: nhsuk/profiles-db-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}
    - mongo-db:mongo

  mongo-db:
    image: mongo:3.4
